eseguibile.3.1:programma.o posizione.o
	g++ programma.o posizione.o -o eseguibile.3.1

programma.o: programma.cpp posizione.h
	g++ -c programma.cpp

posizione.o: posizione.cpp posizione.h
	g++ -c posizione.cpp
