eseguibile.7.2:programma.o integrale.o
	g++ programma.o integrale.o -o eseguibile.7.2

programma.o:programma.cpp integrale.h funzioneBase.h seno.h
	g++ -c programma.cpp -o programma.o 

integrale.o:integrale.cpp funzioneBase.h integrale.h
	g++ -c integrale.cpp
